# Generated by Django 4.0.1 on 2022-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(default='0', max_length=100)),
                ('image', models.FileField(default='test decor image', upload_to='shirtimages')),
            ],
            options={
                'db_table': 'shirt',
            },
        ),
    ]
