# Generated by Django 4.0.1 on 2022-02-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirtsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='decoration',
            table='shirts',
        ),
    ]
