# Generated by Django 4.0.1 on 2022-02-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shirtsapp', '0002_alter_decoration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('shirtdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirtsapp.decoration')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
