# Generated by Django 4.0.1 on 2022-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shirtdetails',
            field=models.CharField(max_length=100),
        ),
    ]
